# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 895518816f5af3aa6fa8372297b6a199642eeedbcfc949ff5148202d35bc40d112de06f40616a50513621c29da18a3e5b45567624a4e534b32cd766e5ab21244

test:
  secret_key_base: c0b35721c3e4e30a95847019f1d6a972243b43fb57423b0b9291edf7548269d2d30e23bf0e1cec409eec51e6b630e5fc1862c6a7552518499458f05aa643ea38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
